### ISSUE TITLE
Call to undefined method "getForeignKeyName" on Morph-Relations

### ISSUE THREAD

**Issue by jheusinger** [cybex-gmbh/laravel-reflector#11]
Laravel removed the getForeignKeyName-Method from a few Relations like MorphToMany within a minor version.
Due to this change the ModelReflector will start causing Exceptions when using `getModelRelations` on a Model with one of the affected Relations.

> [previous exception] [object] (BadMethodCallException(code: 0): Call to undefined method Illuminate\\Database\\Eloquent\\Relations\\MorphToMany::getForeignKeyName() at /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php:71)
[stacktrace]
> 0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(36): Illuminate\\Database\\Eloquent\\Relations\\Relation::throwBadMethodCallException('getForeignKeyNa...')
> 1 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Traits/ForwardsCalls.php(52): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'getForeignKeyNa...', Array)
> 2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Relations/Relation.php(491): Illuminate\\Database\\Eloquent\\Relations\\Relation->forwardDecoratedCallTo(Object(Illuminate\\Database\\Eloquent\\Builder), 'getForeignKeyNa...', Array)
> 3 /var/www/html/vendor/cybex/laravel-reflector/src/ModelReflector.php(110): Illuminate\\Database\\Eloquent\\Relations\\Relation->__call('getForeignKeyNa...', Array)
> 4 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(338): Cybex\\ModelReflector\\ModelReflector->getModelRelations(Object(App\\Models\\Role))

**Comment by gael-connan-cybex** [comment]
volumes:
      - '.:/var/www/html'
      - '../packages:/var/www/packages'


        "cybex/laravel-reflector": "@dev",

        ]
    },
    "repositories": [
        {
            "type": "path",
            "url": "../packages/laravel-reflector"
        }
    ]
}
